# Generated by Django 4.2.7 on 2023-11-21 04:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42, verbose_name='Название')),
                ('intro', models.CharField(max_length=250, verbose_name='Вступление')),
                ('text', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(default=datetime.datetime.now, verbose_name='Срок набора команды')),
                ('tags', models.CharField(max_length=64, verbose_name='Категории')),
                ('owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
