# Generated by Django 4.2.7 on 2023-11-23 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_alter_teams_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JoinInTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Информация о заявителе')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('team_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_boss', to='teams.teams')),
            ],
        ),
    ]
