# Generated by Django 4.2.7 on 2023-11-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teams_owner_joininteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joininteam',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='joininteam',
            name='team_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_boss', to='teams.teams'),
        ),
    ]
