# Generated by Django 4.2.7 on 2023-11-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_joininteam_options_alter_joininteam_team_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininteam',
            name='title',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Название'),
        ),
    ]
