version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: find_team_d
    env_file:
      - .env
    command: ["docker/app.sh"]
    ports:
      - 8080:8000
    image: find_team_d
    volumes:
      - static_volume:/find_team/static

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: find_team_d_nginx
    image: find_team_d_nginx
    volumes:
      - static_volume:/find_team/static
#      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"
    depends_on:
      - app

volumes:
  static_volume:
